### PR TITLE
Added Longest Common Subsequence Question

### PR DESCRIPTION
**Pull request by S-Swaroop**
I have completed the task 1 but am stuck in task 2, need help

### CODE REVIEW

**Comment by Kushal997-das** [comment]
> I have completed the task 1 but am stuck in task 2, need help

Hey please read the raedme.md file very carefully then send PR both task1 and task2 need little bit changes .

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Need changes @S-Swaroop

**Comment by S-Swaroop** [comment]
okay working on it

**Comment by S-Swaroop** [comment]
made changes, please check @Kushal997-das

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Add your portfolio like [this](https://github.com/S-Swaroop/Hacktoberfest_2021/tree/master/1.%20Beginner%20level/TASK%20%232)

**Review by Kushal997-das — APPROVED** [review]
LGTM 👍

**Comment by Kushal997-das** [comment]
> LGTM 👍

@S-Swaroop This file contains conflict please send the PR again thanks

**Pull request merged**
