### PR TITLE
Java Program to find the factorial of a number.

### PR DESCRIPTION
**Pull request by RubenFalcao14**

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Add details over [here](https://github.com/RubenFalcao14/Hacktoberfest_2021/blob/master/1.%20Beginner%20level/TASK%20%231/data.json)

**Comment by RubenFalcao14** [comment]
Done.

**Comment by Kushal997-das** [comment]
> Done.

Send your all changes in single PR 👍

**Comment by RubenFalcao14** [comment]
okay. Thanks a lot..

**Comment by baidya45** [comment]
Can I still contribute in this

**Pull request closed without merging**
