### PR TITLE
Added a hackerrank problem

### PR DESCRIPTION
**Pull request by AnuragThePathak**
Added solution to this question (in C++) from hackerrank https://www.hackerrank.com/challenges/mini-max-sum/problem .

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Task #2 URL is not working properly @AnuragThePathak

**Comment by AnuragThePathak** [comment]
@Kushal997-das are you talking about the image url (https://github.com/Kushal997-das/Hacktoberfest_2021/blob/master/1.%20Beginner%20level/TASK%20%232/Profiles/AnuragThePathak.jpg)?

**Comment by Kushal997-das** [comment]
> @Kushal997-das are you talking about the image url (https://github.com/Kushal997-das/Hacktoberfest_2021/blob/master/1.%20Beginner%20level/TASK%20%232/Profiles/AnuragThePathak.jpg)?

Yes

**Review by AnuragThePathak — COMMENTED** [review]
Fixed image URL issue.

**Comment by Kushal997-das** [comment]
> Fixed image URL issue.

Still not solved ok ill see that one:)

**Review by Kushal997-das — APPROVED** [review]
This branch contains conflict please send PR again Thanks :)

**Comment by AnuragThePathak** [comment]
> LGTM +1

I undserstood the issue now it points to the image link in your master branch which will be active after it gets merged.

**Comment by Kushal997-das** [comment]
> > LGTM +1
> 
> I undserstood the issue now it points to the image link in your master branch which will be active after it gets merged.

Send PR again

**Pull request closed without merging**
