### PR TITLE
I am Vipul this is my first time making a pr

### PR DESCRIPTION
**Pull request by vipul-vaishnav**
as stated i have solved a leet code(programming) problem and added the question.md and Solution.java file, Thank You

### CODE REVIEW

**Comment by vipul-vaishnav** [comment]
I am Vipul Vaishnav, this is my github username @vipul-vaishnav

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Need changes

**Comment by vipul-vaishnav** [comment]
> Need changes

Can you please elaborate what changes you need, that will be really helpful

**Comment by vipul-vaishnav** [comment]
Made some changes in files and added name and username in data.json file.

**Review by Kushal997-das — APPROVED** [review]
LGTM 👍

**Comment by vipul-vaishnav** [comment]
Thank you

**Pull request merged**
