### PR TITLE
Hackerrank question on alogos

### PR DESCRIPTION
**Pull request by AnuragThePathak**
I think image will be shown once it gets merged.

### CODE REVIEW

**Comment by Kushal997-das** [comment]
> I think image will be shown once it gets merged.

No @AnuragThePathak Btw did you put this [URL](https://github.com/AnuragThePathak/Hacktoberfest_2021/blob/AnuragPathak/1.%20Beginner%20level/TASK%20%232/Profiles/AnuragThePathak.jpg) ?

**Comment by AnuragThePathak** [comment]
> > I think image will be shown once it gets merged.
> 
> No @AnuragThePathak Btw did you put this [URL](https://github.com/AnuragThePathak/Hacktoberfest_2021/blob/AnuragPathak/1.%20Beginner%20level/TASK%20%232/Profiles/AnuragThePathak.jpg) ?

Yes I have put it but it points to url in your repo, not the forked one by me.

**Comment by Kushal997-das** [comment]
> > > I think image will be shown once it gets merged.
> > 
> > 
> > No @AnuragThePathak Btw did you put this [URL](https://github.com/AnuragThePathak/Hacktoberfest_2021/blob/AnuragPathak/1.%20Beginner%20level/TASK%20%232/Profiles/AnuragThePathak.jpg) ?
> 
> Yes I have put it but it points to url in your repo, not the forked one by me.

Ok i'll merge

**Review by Kushal997-das — APPROVED** [review]
LGTM 👍

**Comment by Kushal997-das** [comment]
> I think image will be shown once it gets merged.

You put wrong URL now it's fine you can see in my repo and code was not appropriate.

**Comment by AnuragThePathak** [comment]
Sorry for the inconvenience I have caused, I however got to learn quite a lot about Github by making multiple PRs and encountered merge conflict for the first time.

**Pull request merged**
