### PR TITLE
Prrint3 nodes

### PR DESCRIPTION
**Pull request by ojaswinis**

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
See @ojaswinis you missed something please see other work you will get

**Comment by Kushal997-das** [comment]
> See @ojaswinis you missed something please see other work you will get

Hey @ojaswinis please mention the extension like solution.java , solution.cpp etc. in [this](https://github.com/ojaswinis/Hacktoberfest_2021/blob/PRRINT3NODES/1.%20Beginner%20level/TASK%20%231/solution)
More over don't send PR separately. As of now i''ll  merge but in future do with using command.

**Comment by ojaswinis** [comment]
bhaiya i have renamed file

**Comment by Kushal997-das** [comment]
> bhaiya i have renamed file

see the structure of file under the TASK #1 you have to create one folder like [this](https://github.com/Kushal997-das/Hacktoberfest_2021/tree/master/1.%20Beginner%20level/TASK%20%231) then under that particular folder add your program . 

P.S. Don't take it as a burden because this is happen when you contribute something for the first time.

**Pull request closed without merging**
